on:
  workflow_call:
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Get app version
        id: get_version
        uses: ./.github/actions/get-version

      - name: Create tag if not exists
        id: create_tag
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"
          echo "Detected tag: $TAG"

          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping."
            echo "created=false" >> $GITHUB_OUTPUT
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag "$TAG"
            git push origin "$TAG"
            echo "created=true" >> $GITHUB_OUTPUT
            echo "âœ… Created and pushed tag $TAG"
          fi

      - name: Prepare Release Message
        if: steps.create_tag.outputs.created == 'true'
        run: |
          sed "s|RELEASE_TAG|v${{ steps.get_version.outputs.version }}|g" \
            .github/release_message.md >> release.md

      - name: Download Android artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-release
          path: android-release/

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-release
          path: windows-release/
      
      - name: Download iOS artifacts
        if: false
        uses: actions/download-artifact@v4
        with:
          name: ios-release
          path: ios-release/

      - name: Create GitHub Release
        if: steps.create_tag.outputs.created == 'true'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.get_version.outputs.version }}"
          name: "v${{ steps.get_version.outputs.version }}"
          draft: true
          files: |
            android-release/**/*.apk
            windows-release/**
          body_path: release.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete existing release assets
        if: steps.create_tag.outputs.created == 'false'
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ steps.get_version.outputs.version }}"
          assets: "*"

      - name: Update GitHub Release
        if: steps.create_tag.outputs.created == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.get_version.outputs.version }}"
          name: "v${{ steps.get_version.outputs.version }}"
          files: |
            android-release/**/*.apk
            windows-release/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload AAB to Google Play Store
        if: steps.create_tag.outputs.created == 'true'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: de.unboundtech.defyxvpn
          releaseFiles: android-release/**/*.aab
          track: internal
          status: draft

      - name: Upload to TestFlight
        if: false
        uses: apple-actions/upload-testflight-build@v3
        with:
          app-path: build/ios/ipa/Runner.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}